# Generated by Django 5.0.14 on 2025-11-15 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format 09123456789', regex='^09[0-9]{9}$')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('duplicate', 'Duplicate'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leads',
                'indexes': [models.Index(fields=['phone_number'], name='leads_phone_n_99abde_idx'), models.Index(fields=['created_at'], name='leads_created_e6e479_idx'), models.Index(fields=['status'], name='leads_status_94f025_idx')],
            },
        ),
    ]
